# Generated by Django 3.2.24 on 2025-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default='main', max_length=50, verbose_name='Название меню'),
        ),
    ]
