# Generated by Django 4.2.23 on 2025-06-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_menuitem_menu_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="menu_name",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="app.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="app.menu",
            ),
            preserve_default=False,
        ),
    ]
